"""ORM models."""

from app.models.ai_job import AIJob, AIProposal
from app.models.audit_event import AuditEvent
from app.models.auth_session import AuthSession
from app.models.dataset import (
    AnalysisArtifact,
    AnalysisRun,
    Dataset,
    DatasetColumn,
    DatasetProfile,
    DatasetVersion,
    Figure,
    ManuscriptAssetRef,
    ReproducibilityManifest,
    Table,
)
from app.models.email_verification import EmailVerificationToken
from app.models.engagement import (
    AnalyticsEvent,
    DailyGoal,
    InAppNotification,
    NotificationPreference,
    ProgressEvent,
    ProjectMilestone,
)
from app.models.enums import (
    AIJobStatus,
    AIOperation,
    AIProposalStatus,
    AnalysisOperation,
    AnalysisRunStatus,
    AnalyticsEventType,
    AuditAction,
    ClaimSupportStatus,
    DailyGoalType,
    DatasetColumnType,
    DatasetProvenanceType,
    EvidenceRelation,
    ExportArtifactKind,
    ExportJobStatus,
    ExportTemplateId,
    ExportValidationSeverity,
    FactCategory,
    FactSourceType,
    FactVerificationStatus,
    FigureKind,
    FileKind,
    FileProcessingStatus,
    FindingResolutionAction,
    MilestoneType,
    NotificationKind,
    ProjectStatus,
    ReferenceVerificationStatus,
    RetentionPolicy,
    SectionStatus,
    SectionType,
    SimilarityFindingClass,
    SimilarityJobStatus,
    SimilaritySourceKind,
    SubscriptionPlan,
    TableKind,
    UserStatus,
    VersionAuthorType,
)
from app.models.evidence import CitationMention, ClaimProvenance, EvidenceLink
from app.models.export import ExportArtifact, ExportDownload, ExportJob
from app.models.manuscript import Manuscript, ManuscriptSection, ManuscriptVersion
from app.models.oauth_account import OAuthAccount
from app.models.password_reset import PasswordResetToken
from app.models.project import Project
from app.models.project_fact import ProjectFact
from app.models.project_file import (
    ChunkEmbedding,
    DocumentChunk,
    DocumentPage,
    ExtractedDocument,
    FileProcessingJob,
    ProjectFile,
)
from app.models.reference import Reference, ReferenceAuthor, ReferenceIdentifier
from app.models.similarity import (
    FindingResolution,
    ReportCoverage,
    SimilarityFinding,
    SimilarityJob,
    SimilarityReport,
    SimilaritySource,
)
from app.models.user import User

__all__ = [
    "AIJob",
    "AIJobStatus",
    "AIOperation",
    "AIProposal",
    "AIProposalStatus",
    "AnalysisArtifact",
    "AnalysisOperation",
    "AnalysisRun",
    "AnalysisRunStatus",
    "AnalyticsEvent",
    "AnalyticsEventType",
    "AuditAction",
    "AuditEvent",
    "AuthSession",
    "ChunkEmbedding",
    "CitationMention",
    "ClaimProvenance",
    "ClaimSupportStatus",
    "DailyGoal",
    "DailyGoalType",
    "Dataset",
    "DatasetColumn",
    "DatasetColumnType",
    "DatasetProfile",
    "DatasetProvenanceType",
    "DatasetVersion",
    "DocumentChunk",
    "DocumentPage",
    "EmailVerificationToken",
    "EvidenceLink",
    "EvidenceRelation",
    "ExportArtifact",
    "ExportArtifactKind",
    "ExportDownload",
    "ExportJob",
    "ExportJobStatus",
    "ExportTemplateId",
    "ExportValidationSeverity",
    "ExtractedDocument",
    "FactCategory",
    "FactSourceType",
    "FactVerificationStatus",
    "Figure",
    "FigureKind",
    "FileKind",
    "FileProcessingJob",
    "FileProcessingStatus",
    "FindingResolution",
    "FindingResolutionAction",
    "InAppNotification",
    "Manuscript",
    "ManuscriptAssetRef",
    "ManuscriptSection",
    "ManuscriptVersion",
    "MilestoneType",
    "NotificationKind",
    "NotificationPreference",
    "OAuthAccount",
    "PasswordResetToken",
    "ProgressEvent",
    "Project",
    "ProjectFact",
    "ProjectFile",
    "ProjectMilestone",
    "ProjectStatus",
    "Reference",
    "ReferenceAuthor",
    "ReferenceIdentifier",
    "ReferenceVerificationStatus",
    "ReportCoverage",
    "ReproducibilityManifest",
    "RetentionPolicy",
    "SectionStatus",
    "SectionType",
    "SimilarityFinding",
    "SimilarityFindingClass",
    "SimilarityJob",
    "SimilarityJobStatus",
    "SimilarityReport",
    "SimilaritySource",
    "SimilaritySourceKind",
    "SubscriptionPlan",
    "Table",
    "TableKind",
    "User",
    "UserStatus",
    "VersionAuthorType",
]
