"""ZIP packaging for Overleaf, figures, datasets, and full submission packages."""

from __future__ import annotations

import io
import json
import zipfile
from typing import Any

from app.services.export.canonical import CanonicalManuscript
from app.services.export.latex_render import render_bibtex, render_latex


def build_overleaf_zip(
    manuscript: CanonicalManuscript,
    *,
    figure_bytes: dict[str, bytes] | None = None,
) -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("main.tex", render_latex(manuscript))
        zf.writestr("references.bib", render_bibtex(manuscript))
        zf.writestr(
            "README.txt",
            (
                "Overleaf-compatible starting package generated by ResearchForge.\n"
                "These templates are compatible starting templates, not officially "
                "certified publisher formats. Verify current submission requirements.\n"
            ),
        )
        figures = figure_bytes or {}
        for fig in manuscript.figures:
            fname = fig.filename or f"figure_{fig.number}.png"
            data = figures.get(fig.id) or figures.get(fname)
            if data:
                zf.writestr(f"figures/{fname}", data)
            else:
                zf.writestr(
                    f"figures/{fname}.missing.txt",
                    f"Missing figure asset for {fig.id}\n",
                )
    return buf.getvalue()


def build_figures_zip(figure_bytes: dict[str, bytes], manifest: list[dict[str, Any]]) -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("figures_manifest.json", json.dumps(manifest, indent=2))
        for name, data in figure_bytes.items():
            zf.writestr(name, data)
    return buf.getvalue()


def build_dataset_manifest_zip(payload: dict[str, Any]) -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("reproducibility_manifest.json", json.dumps(payload, indent=2, default=str))
        zf.writestr(
            "README.txt",
            (
                "Dataset and reproducibility manifest package.\n"
                "Synthetic or simulated data must remain labeled in downstream use.\n"
            ),
        )
    return buf.getvalue()


def build_submission_package(
    *,
    files: dict[str, bytes],
    provenance: dict[str, Any],
) -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for name, data in files.items():
            zf.writestr(name, data)
        zf.writestr("provenance_manifest.json", json.dumps(provenance, indent=2, default=str))
        zf.writestr(
            "SUBMISSION_README.txt",
            (
                "Complete submission package from ResearchForge.\n"
                "Templates are compatible starting templates only.\n"
                "Authors must verify current journal/conference requirements.\n"
                "Similarity reports require human review and are not plagiarism guarantees.\n"
            ),
        )
    return buf.getvalue()


def list_zip_names(data: bytes) -> list[str]:
    with zipfile.ZipFile(io.BytesIO(data), "r") as zf:
        return sorted(zf.namelist())
