#!/usr/bin/env node
/**
 * Generate cryptographically strong secrets for local development.
 * Prints values suitable for .env — does not write files unless --write is passed.
 */
import { randomBytes } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const envPath = resolve(root, '.env');
const examplePath = resolve(root, '.env.example');

function secret(bytes = 48) {
  return randomBytes(bytes).toString('base64url');
}

const values = {
  SECRET_KEY: secret(),
  CSRF_SECRET: secret(),
};

const lines = [
  '# Generated by scripts/generate-secrets.mjs',
  `SECRET_KEY=${values.SECRET_KEY}`,
  `CSRF_SECRET=${values.CSRF_SECRET}`,
];

console.log(lines.join('\n'));

const write = process.argv.includes('--write');
if (!write) {
  console.log('\n# Tip: re-run with --write to merge into .env (created from .env.example if missing)');
  process.exit(0);
}

let content = '';
if (existsSync(envPath)) {
  content = readFileSync(envPath, 'utf8');
} else if (existsSync(examplePath)) {
  content = readFileSync(examplePath, 'utf8');
  console.log(`\nCreated .env from .env.example`);
} else {
  content = '';
}

for (const [key, value] of Object.entries(values)) {
  const pattern = new RegExp(`^${key}=.*$`, 'm');
  if (pattern.test(content)) {
    content = content.replace(pattern, `${key}=${value}`);
  } else {
    content = `${content.trimEnd()}\n${key}=${value}\n`;
  }
}

writeFileSync(envPath, content.endsWith('\n') ? content : `${content}\n`, 'utf8');
console.log(`\nWrote secrets to ${envPath}`);
